"""schema_update

Revision ID: 13f060b286e3
Revises: 4826288717b7
Create Date: 2026-08-01 10:26:33.483138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13f060b286e3'
down_revision: Union[str, Sequence[str], None] = '4826288717b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import logging
    import sqlalchemy.exc
    
    bind = op.get_bind()
    bind.execute(sa.text("SET search_path TO public, extensions;"))
    has_extension = bind.execute(sa.text("SELECT 1 FROM pg_extension WHERE extname='btree_gist'")).scalar()
    if not has_extension:
        try:
            bind.execute(sa.text("CREATE SCHEMA IF NOT EXISTS extensions;"))
            bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;"))
            bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;"))
        except (sqlalchemy.exc.ProgrammingError, sqlalchemy.exc.DBAPIError) as e:
            if "permission denied" in str(e).lower() or "must be superuser" in str(e).lower():
                logging.warning("Failed to create btree_gist extension. Please run manually: CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;")
            else:
                raise

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_rows')
    op.create_index('uix_company_platform_external_account', 'ad_accounts', ['company_id', 'platform', 'external_account_id'], unique=True, postgresql_where=sa.text('external_account_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_alerts_company_unacked', 'alerts', ['company_id'], unique=False, postgresql_where=sa.text('acknowledged_at IS NULL'))
    op.create_index('ix_alerts_dedup_key', 'alerts', ['dedup_key'], unique=False)
    op.alter_column('audit_log', 'diff',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_audit_log_company_entity', 'audit_log', ['company_id', 'entity_type', 'entity_id'], unique=False)
    op.drop_constraint(op.f('uq_campaign_run_stats_date'), 'campaign_run_stats', type_='unique')
    op.create_index('ix_campaign_run_stats_company_date', 'campaign_run_stats', ['company_id', 'stat_date'], unique=False)
    op.create_index('uq_campaign_run_stats', 'campaign_run_stats', ['company_id', 'campaign_run_id', 'stat_date', 'source', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.alter_column('chat_messages', 'tool_calls_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('fx_rates', sa.Column('from_currency', sa.CHAR(length=3), nullable=False))
    op.add_column('fx_rates', sa.Column('to_currency', sa.CHAR(length=3), nullable=False))
    op.create_unique_constraint('uq_fx_rate_date_currencies_source', 'fx_rates', ['rate_date', 'from_currency', 'to_currency', 'source'])
    op.drop_column('fx_rates', 'base')
    op.drop_column('fx_rates', 'quote')
    op.add_column('import_batches', sa.Column('row_count', sa.Integer(), nullable=False))
    op.add_column('import_batches', sa.Column('error_count', sa.Integer(), nullable=False))
    op.add_column('import_batches', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('import_batches', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_import_batches_company_created', 'import_batches', ['company_id', 'created_at'], unique=False)
    op.drop_column('import_batches', 'column_mapping')
    op.drop_column('import_batches', 'error_rows')
    op.drop_column('import_batches', 'delimiter')
    op.drop_column('import_batches', 'file_hash')
    op.drop_column('import_batches', 'imported_rows')
    op.drop_column('import_batches', 'valid_rows')
    op.drop_column('import_batches', 'encoding')
    op.drop_column('import_batches', 'committed_at')
    op.drop_column('import_batches', 'total_rows')
    op.alter_column('invites', 'email',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_index('ix_invites_company_email', 'invites', ['company_id', 'email'], unique=False)
    op.create_index('ix_invites_email_expires', 'invites', ['email', 'expires_at'], unique=False, postgresql_where=sa.text('accepted_at IS NULL'))
    op.create_index('ix_partner_payouts_company_status_hold', 'partner_payouts', ['company_id', 'status', 'hold_until'], unique=False)
    op.create_index('ix_telegram_link_tokens_user_expires', 'telegram_link_tokens', ['user_id', 'expires_at'], unique=False)
    op.execute("UPDATE transactions SET fx_rate_to_base = 1.0 WHERE fx_rate_to_base IS NULL")
    op.alter_column('transactions', 'fx_rate_to_base',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.create_index('ix_transactions_company_occurred_on', 'transactions', ['company_id', 'occurred_on'], unique=False)
    op.create_index('ix_transactions_company_type_category', 'transactions', ['company_id', 'type', 'category'], unique=False)
    op.drop_column('transactions', 'amount_in_base')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_index('uix_company_email', 'users', ['company_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.execute("""
        ALTER TABLE compensation_plans 
        ADD CONSTRAINT excl_comp_plan_overlap 
        EXCLUDE USING gist (
            company_id WITH =, 
            user_id WITH =, 
            daterange(effective_from, COALESCE(effective_to, 'infinity'), '[]') WITH &&
        ) WHERE (deleted_at IS NULL);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE compensation_plans DROP CONSTRAINT IF EXISTS excl_comp_plan_overlap;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_company_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('amount_in_base', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.drop_index('ix_transactions_company_type_category', table_name='transactions')
    op.drop_index('ix_transactions_company_occurred_on', table_name='transactions')
    op.alter_column('transactions', 'fx_rate_to_base',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_index('ix_telegram_link_tokens_user_expires', table_name='telegram_link_tokens')
    op.drop_index('ix_partner_payouts_company_status_hold', table_name='partner_payouts')
    op.drop_index('ix_invites_email_expires', table_name='invites', postgresql_where=sa.text('accepted_at IS NULL'))
    op.drop_index('ix_invites_company_email', table_name='invites')
    op.alter_column('invites', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('import_batches', sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_batches', sa.Column('committed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('import_batches', sa.Column('encoding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('import_batches', sa.Column('valid_rows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_batches', sa.Column('imported_rows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_batches', sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('import_batches', sa.Column('delimiter', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('import_batches', sa.Column('error_rows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_batches', sa.Column('column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_import_batches_company_created', table_name='import_batches')
    op.alter_column('import_batches', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('import_batches', 'completed_at')
    op.drop_column('import_batches', 'error_count')
    op.drop_column('import_batches', 'row_count')
    op.add_column('fx_rates', sa.Column('quote', sa.CHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('fx_rates', sa.Column('base', sa.CHAR(length=3), autoincrement=False, nullable=False))
    op.drop_constraint('uq_fx_rate_date_currencies_source', 'fx_rates', type_='unique')
    op.drop_column('fx_rates', 'to_currency')
    op.drop_column('fx_rates', 'from_currency')
    op.alter_column('chat_messages', 'tool_calls_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('uq_campaign_run_stats', table_name='campaign_run_stats', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_campaign_run_stats_company_date', table_name='campaign_run_stats')
    op.create_unique_constraint(op.f('uq_campaign_run_stats_date'), 'campaign_run_stats', ['company_id', 'campaign_run_id', 'stat_date'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_audit_log_company_entity', table_name='audit_log')
    op.alter_column('audit_log', 'diff',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_alerts_dedup_key', table_name='alerts')
    op.drop_index('ix_alerts_company_unacked', table_name='alerts', postgresql_where=sa.text('acknowledged_at IS NULL'))
    op.drop_index('uix_company_platform_external_account', table_name='ad_accounts', postgresql_where=sa.text('external_account_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('import_rows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parsed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('import_rows_batch_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('import_rows_company_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('import_rows_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('import_rows_pkey'))
    )
    # ### end Alembic commands ###



