"""Add actor_type and source to AuditLog

Revision ID: 20d6e73eefad
Revises: 13f060b286e3
Create Date: 2026-08-01 10:43:39.137220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d6e73eefad'
down_revision: Union[str, Sequence[str], None] = '13f060b286e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('actor_type', sa.String(), server_default='user', nullable=False))
    op.add_column('audit_log', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'source')
    op.drop_column('audit_log', 'actor_type')
    # ### end Alembic commands ###
