"""Add alert thresholds

Revision ID: 6033c46a54ae
Revises: 20d6e73eefad
Create Date: 2026-08-01 11:09:07.878541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6033c46a54ae'
down_revision: Union[str, Sequence[str], None] = '20d6e73eefad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('alert_runway_threshold_days', sa.Integer(), server_default='30', nullable=False))
    op.add_column('companies', sa.Column('alert_roi_threshold', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False))
    op.add_column('companies', sa.Column('alert_stalled_data_days', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'alert_stalled_data_days')
    op.drop_column('companies', 'alert_roi_threshold')
    op.drop_column('companies', 'alert_runway_threshold_days')
    # ### end Alembic commands ###
