"""add_connector_configs

Revision ID: b7d23a9b1c1e
Revises: f8d61e75a111
Create Date: 2026-09-03 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d23a9b1c1e'
down_revision: Union[str, None] = 'f8d61e75a111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False, server_default='60'),
    sa.Column('last_attempted_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_connector_configs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_configs')),
    sa.UniqueConstraint('company_id', 'connector_name', name='uix_company_connector'),
    sa.CheckConstraint("status IN ('active', 'paused', 'failing', 'unauthorized')", name="check_connector_status")
    )
    op.create_index('ix_connector_configs_next_sync', 'connector_configs', ['status', 'next_sync_at'], unique=False)
    
    # Enable RLS
    op.execute('ALTER TABLE connector_configs ENABLE ROW LEVEL SECURITY')
    op.execute('CREATE POLICY tenant_isolation_policy ON connector_configs USING (company_id = current_setting(\\'app.company_id\\', TRUE)::uuid)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON connector_configs')
    op.drop_index('ix_connector_configs_next_sync', table_name='connector_configs')
    op.drop_table('connector_configs')
    # ### end Alembic commands ###
