with open('app/db/models/campaigns.py', 'a', encoding='utf-8') as f:
    f.write('    purchased_on: Mapped[date] = mapped_column(Date, nullable=False)\n')
    f.write('    expires_on: Mapped[date | None] = mapped_column(Date, nullable=True)\n')
    f.write('    status: Mapped[str] = mapped_column(String, default=\'active\', nullable=False)\n')
    f.write('    transaction_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("transactions.id"), nullable=True)\n')
    f.write('\n')
    f.write('    __table_args__ = (\n')
    f.write('        CheckConstraint("type IN (\'proxy\', \'card\', \'account_service\', \'other\')", name="check_consumable_type"),\n')
    f.write('        CheckConstraint("status IN (\'active\', \'expired\', \'burned\')", name="check_consumable_status"),\n')
    f.write('    )\n')
