/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users Me */
        get: operations["read_users_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Csv
         * @description Step 1: Upload CSV, create ImportBatch, insert ImportRows.
         */
        post: operations["upload_csv_api_v1_imports_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Import Batch
         * @description Step 2: Commit batch using column_mapping.
         *     Calls the commit_batch service.
         */
        post: operations["commit_import_batch_api_v1_imports__batch_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Import Batch */
        delete: operations["delete_import_batch_api_v1_imports__batch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consumables/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Consumable */
        post: operations["create_consumable_api_v1_consumables__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tx */
        get: operations["list_tx_api_v1_transactions__get"];
        put?: never;
        /** Create Tx */
        post: operations["create_tx_api_v1_transactions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tx */
        get: operations["get_tx_api_v1_transactions__id__get"];
        put?: never;
        post?: never;
        /** Delete Tx */
        delete: operations["delete_tx_api_v1_transactions__id__delete"];
        options?: never;
        head?: never;
        /** Update Tx */
        patch: operations["update_tx_api_v1_transactions__id__patch"];
        trace?: never;
    };
    "/api/v1/transactions/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary Tx */
        get: operations["summary_tx_api_v1_transactions_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pnl Report */
        get: operations["pnl_report_api_v1_reports_pnl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cash Flow Report */
        get: operations["cash_flow_report_api_v1_reports_cash_flow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Score Report */
        get: operations["health_score_report_api_v1_reports_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/diagnostics/spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spend Discrepancy Report */
        get: operations["spend_discrepancy_report_api_v1_reports_diagnostics_spend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ad-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ad Accounts */
        get: operations["list_ad_accounts_api_v1_ad_accounts__get"];
        put?: never;
        /** Create Ad Account */
        post: operations["create_ad_account_api_v1_ad_accounts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ad-accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ad Account */
        get: operations["get_ad_account_api_v1_ad_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ad Account */
        patch: operations["update_ad_account_api_v1_ad_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/ad-accounts/{account_id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Cost */
        get: operations["get_account_cost_api_v1_ad_accounts__account_id__cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaign-runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaign Runs */
        get: operations["list_campaign_runs_api_v1_campaign_runs__get"];
        put?: never;
        /** Create Campaign Run */
        post: operations["create_campaign_run_api_v1_campaign_runs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaign-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign Run */
        get: operations["get_campaign_run_api_v1_campaign_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Campaign Run */
        patch: operations["update_campaign_run_api_v1_campaign_runs__run_id__patch"];
        trace?: never;
    };
    "/api/v1/campaign-run-stats/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert Campaign Run Stat */
        post: operations["upsert_campaign_run_stat_api_v1_campaign_run_stats_upsert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaign-run-stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaign Run Stats */
        get: operations["list_campaign_run_stats_api_v1_campaign_run_stats__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_api_v1_webhooks_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Alert */
        post: operations["acknowledge_alert_api_v1_alerts__id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat With Analyst */
        post: operations["chat_with_analyst_api_v1_chat__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdAccountCreate */
        AdAccountCreate: {
            /** Platform */
            platform: string;
            /** External Account Id */
            external_account_id?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Vertical */
            vertical?: string | null;
            /** Geo */
            geo?: string | null;
            /** Prepared By User Id */
            prepared_by_user_id?: string | null;
            /** Assigned Buyer Id */
            assigned_buyer_id?: string | null;
        };
        /** AdAccountOut */
        AdAccountOut: {
            /** Platform */
            platform: string;
            /** External Account Id */
            external_account_id?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Vertical */
            vertical?: string | null;
            /** Geo */
            geo?: string | null;
            /** Prepared By User Id */
            prepared_by_user_id?: string | null;
            /** Assigned Buyer Id */
            assigned_buyer_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Compunknown Id
             * Format: uuid
             */
            compunknown_id: string;
            /** Banned At */
            banned_at?: string | null;
        };
        /** AdAccountUpdate */
        AdAccountUpdate: {
            /** Platform */
            platform?: string | null;
            /** External Account Id */
            external_account_id?: string | null;
            /** Status */
            status?: string | null;
            /** Vertical */
            vertical?: string | null;
            /** Geo */
            geo?: string | null;
            /** Prepared By User Id */
            prepared_by_user_id?: string | null;
            /** Assigned Buyer Id */
            assigned_buyer_id?: string | null;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_csv_api_v1_imports_upload_post */
        Body_upload_csv_api_v1_imports_upload_post: {
            /** File */
            file: string;
        };
        /** CampaignRunCreate */
        CampaignRunCreate: {
            /** Campaign Id */
            campaign_id?: string | null;
            /** Ad Account Id */
            ad_account_id?: string | null;
            /**
             * Buyer Id
             * Format: uuid
             */
            buyer_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Note */
            note?: string | null;
        };
        /** CampaignRunOut */
        CampaignRunOut: {
            /** Campaign Id */
            campaign_id?: string | null;
            /** Ad Account Id */
            ad_account_id?: string | null;
            /**
             * Buyer Id
             * Format: uuid
             */
            buyer_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Note */
            note?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Compunknown Id
             * Format: uuid
             */
            compunknown_id: string;
        };
        /** CampaignRunStatCreate */
        CampaignRunStatCreate: {
            /**
             * Campaign Run Id
             * Format: uuid
             */
            campaign_run_id: string;
            /**
             * Stat Date
             * Format: date
             */
            stat_date: string;
            /**
             * Spend
             * Format: decimal
             * @default 0.00
             */
            spend: string;
            /**
             * Revenue
             * Format: decimal
             * @default 0.00
             */
            revenue: string;
            /** Currency */
            currency: string;
            /**
             * Fx Rate To Base
             * Format: decimal
             */
            fx_rate_to_base: string;
            /** Source */
            source: string;
            /** External Id */
            external_id?: string | null;
        };
        /** CampaignRunStatOut */
        CampaignRunStatOut: {
            /**
             * Campaign Run Id
             * Format: uuid
             */
            campaign_run_id: string;
            /**
             * Stat Date
             * Format: date
             */
            stat_date: string;
            /**
             * Spend
             * Format: decimal
             */
            spend?: string;
            /**
             * Revenue
             * Format: decimal
             */
            revenue?: string;
            /** Currency */
            currency: string;
            /**
             * Fx Rate To Base
             * Format: decimal
             */
            fx_rate_to_base: string;
            /** Source */
            source: string;
            /** External Id */
            external_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Compunknown Id
             * Format: uuid
             */
            compunknown_id: string;
        };
        /** CampaignRunUpdate */
        CampaignRunUpdate: {
            /** Campaign Id */
            campaign_id?: string | null;
            /** Ad Account Id */
            ad_account_id?: string | null;
            /** Buyer Id */
            buyer_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Status */
            status?: string | null;
            /** Note */
            note?: string | null;
        };
        /** CashFlowResult */
        CashFlowResult: {
            /**
             * Transaction Balance
             * Format: decimal
             */
            transaction_balance: string;
            /**
             * Held Payouts
             * Format: decimal
             */
            held_payouts: string;
            /**
             * Available Balance
             * Format: decimal
             */
            available_balance: string;
            /** Average Daily Spend 30D */
            average_daily_spend_30d: string | null;
            /** Runway Days */
            runway_days: number | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Message */
            message: string;
        };
        /** CommitImportRequest */
        CommitImportRequest: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Column Mapping */
            column_mapping: {
                [key: string]: string;
            };
        };
        /** CommitResult */
        CommitResult: {
            /** Imported */
            imported: number;
            /** Duplicates */
            duplicates: number;
        };
        /** ConsumableCreate */
        ConsumableCreate: {
            /** Type */
            type: string;
            /** Identifier */
            identifier?: string | null;
            /**
             * Cost
             * Format: decimal
             */
            cost: string;
            /** Currency */
            currency: string;
        };
        /** ConsumableOut */
        ConsumableOut: {
            /** Status */
            status: string;
            /** Identifier */
            identifier?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthScoreResult */
        HealthScoreResult: {
            /** Health Score */
            health_score: number;
        };
        /** PnLResult */
        PnLResult: {
            /**
             * Revenue
             * Format: decimal
             */
            revenue: string;
            /**
             * Ad Spend
             * Format: decimal
             */
            ad_spend: string;
            /**
             * Gross Profit
             * Format: decimal
             */
            gross_profit: string;
            /**
             * Consumables
             * Format: decimal
             */
            consumables: string;
            /**
             * Operating Expenses
             * Format: decimal
             */
            operating_expenses: string;
            /**
             * Ebitda
             * Format: decimal
             */
            ebitda: string;
            /**
             * Depreciation
             * Format: decimal
             */
            depreciation: string;
            /**
             * Ebit
             * Format: decimal
             */
            ebit: string;
            /**
             * Interest
             * Format: decimal
             */
            interest: string;
            /**
             * Ebt
             * Format: decimal
             */
            ebt: string;
            /**
             * Tax
             * Format: decimal
             */
            tax: string;
            /**
             * Net Profit
             * Format: decimal
             */
            net_profit: string;
            /** Gross Margin */
            gross_margin: string | null;
            /** Ebitda Margin */
            ebitda_margin: string | null;
            /** Ebit Margin */
            ebit_margin: string | null;
            /** Ebt Margin */
            ebt_margin: string | null;
            /** Net Margin */
            net_margin: string | null;
            /** Margin */
            margin: string | null;
        };
        /** SpendDiscrepancyResult */
        SpendDiscrepancyResult: {
            /**
             * Tracker Spend
             * Format: decimal
             */
            tracker_spend: string;
            /**
             * Actual Spend
             * Format: decimal
             */
            actual_spend: string;
            /**
             * Discrepancy
             * Format: decimal
             */
            discrepancy: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Type */
            type: string;
            /** Category */
            category: string;
            /**
             * Amount
             * Format: decimal
             */
            amount: string;
            /** Currency */
            currency: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Team Id */
            team_id?: string | null;
            /** Description */
            description?: string | null;
        };
        /** TransactionListResponse */
        TransactionListResponse: {
            /** Items */
            items: components["schemas"]["TransactionOut"][];
            /** Total */
            total: number;
            /**
             * Total Amount
             * Format: decimal
             */
            total_amount: string;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** TransactionOut */
        TransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /**
             * Amount
             * Format: decimal
             */
            amount: string;
            /** Currency */
            currency: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Description */
            description?: string | null;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Team Id */
            team_id?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Batch Id */
            batch_id: string;
            /** Columns */
            columns: string[];
            /** Row Count */
            row_count: number;
            /** Preview */
            preview: {
                [key: string]: unknown;
            }[];
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Compunknown Name */
            compunknown_name: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Compunknown Id */
            compunknown_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    upload_csv_api_v1_imports_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_v1_imports_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_import_batch_api_v1_imports__batch_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_import_batch_api_v1_imports__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_consumable_api_v1_consumables__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumableOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tx_api_v1_transactions__get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tx_api_v1_transactions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tx_api_v1_transactions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tx_api_v1_transactions__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tx_api_v1_transactions__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_tx_api_v1_transactions_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    pnl_report_api_v1_reports_pnl_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_flow_report_api_v1_reports_cash_flow_get: {
        parameters: {
            query?: {
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_score_report_api_v1_reports_health_get: {
        parameters: {
            query?: {
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthScoreResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spend_discrepancy_report_api_v1_reports_diagnostics_spend_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendDiscrepancyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ad_accounts_api_v1_ad_accounts__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdAccountOut"][];
                };
            };
        };
    };
    create_ad_account_api_v1_ad_accounts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdAccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ad_account_api_v1_ad_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ad_account_api_v1_ad_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdAccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_cost_api_v1_ad_accounts__account_id__cost_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaign_runs_api_v1_campaign_runs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunOut"][];
                };
            };
        };
    };
    create_campaign_run_api_v1_campaign_runs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_run_api_v1_campaign_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_run_api_v1_campaign_runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRunUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_campaign_run_stat_api_v1_campaign_run_stats_upsert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRunStatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunStatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaign_run_stats_api_v1_campaign_run_stats__get: {
        parameters: {
            query?: {
                campaign_run_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRunStatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_webhook_api_v1_webhooks_telegram_post: {
        parameters: {
            query?: never;
            header?: {
                "x-telegram-bot-api-secret-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_analyst_api_v1_chat__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}

